# Generated by Django 3.2.5 on 2022-01-20 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(choices=[(1, 'Piano'), (2, 'Clarinet'), (3, 'Vocals'), (4, 'Drums')])),
                ('paymant_teacher', models.FloatField()),
                ('paymant_student', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(0, 'ПН'), (1, 'ВТ'), (2, 'СР'), (3, 'ЧТ'), (4, 'ПТ'), (5, 'СБ'), (6, 'ВС')])),
            ],
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(9, '09-10'), (10, '10-11'), (11, '11-12'), (12, '12-13'), (13, '13-14'), (14, '14-15'), (15, '15-16'), (16, '16-17'), (17, '17-18'), (18, '18-19'), (19, '19-20')])),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, 'Кларнет-холл'), (2, 'Морской'), (3, 'Полосатый'), (4, 'Зел.Дом'), (5, 'Конса'), (6, 'Барабан'), (7, '1_Этаж')])),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('contact', models.CharField(max_length=30)),
                ('messenger', models.IntegerField(choices=[(1, 'Viber'), (2, 'Telegram'), (3, 'WhatsApp'), (4, 'another')])),
                ('comments', models.CharField(max_length=100, verbose_name='Коментарии')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['-birthday'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30, verbose_name=' Фамилия')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('contact', models.CharField(max_length=30, verbose_name='Номер')),
                ('messenger', models.IntegerField(choices=[(1, 'Viber'), (2, 'Telegram'), (3, 'WhatsApp'), (4, 'another')])),
                ('source', models.CharField(default='АШБ', max_length=30, verbose_name='Источник')),
                ('comments', models.CharField(max_length=100, verbose_name='Коментарии')),
                ('agent_name', models.CharField(max_length=30, verbose_name='Имя представителя')),
                ('agent_type', models.CharField(max_length=30, verbose_name='Вид представителя')),
                ('agent_contact', models.CharField(max_length=30, verbose_name='Номер представителя')),
                ('teachers', models.ManyToManyField(through='schedule.Contract', to='schedule.Teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Ученики',
                'ordering': ['-birthday'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('duration', models.FloatField(default=1)),
                ('type', models.IntegerField(choices=[(1, 'в школе'), (2, 'онлайн из школы'), (3, 'онлайн из дома'), (4, 'вне школы')], default=1)),
                ('state', models.IntegerField(choices=[(1, 'ожидается'), (2, 'состоялось'), (3, 'отменено преподавателем'), (4, 'отменено студентом')], default=1)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.contract')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.office')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.student'),
        ),
        migrations.AddField(
            model_name='contract',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.teacher'),
        ),
    ]
