# Generated by Django 3.0.8 on 2020-07-19 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(choices=[(1, 'Piano'), (2, 'Clarinet'), (3, 'Vocals'), (4, 'Drums')])),
                ('paymant_teacher', models.FloatField()),
                ('paymant_student', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, 'Кларнет-холл'), (2, 'Морской'), (3, 'Полосатый')])),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('type_of_contact', models.CharField(default='мобильный', max_length=10)),
                ('contact', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('type_of_contact', models.CharField(default='мобильный', max_length=10)),
                ('contact', models.CharField(max_length=30)),
                ('teachers', models.ManyToManyField(through='schedule.Contract', to='schedule.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('duration', models.FloatField()),
                ('type', models.IntegerField(choices=[(1, 'в школе'), (2, 'онлайн из школы'), (3, 'онлайн из дома'), (4, 'вне школы')], default=1)),
                ('state', models.IntegerField(choices=[(1, 'ожидается'), (2, 'состоялось'), (3, 'отменено преподавателем'), (4, 'отменено студентом')], default=1)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Contract')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Office')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Student'),
        ),
        migrations.AddField(
            model_name='contract',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Teacher'),
        ),
    ]
