# Generated by Django 3.0.8 on 2020-07-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(1, 'ПН'), (2, 'ВТ'), (3, 'СР'), (4, 'ЧТ'), (5, 'ПТ'), (6, 'СБ'), (7, 'ВС')])),
            ],
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.IntegerField(choices=[(1, 'Кларнет-холл'), (2, 'Морской'), (3, 'Полосатый'), (4, 'Зел.Дом'), (5, 'Конса'), (6, 'Барабан'), (7, '1_Этаж')]),
        ),
    ]
