# Generated by Django 3.2.5 on 2022-01-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='messenger',
            field=models.IntegerField(choices=[(1, 'Viber'), (2, 'Telegram'), (3, 'WhatsApp'), (4, 'another')], default=1),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='messenger',
            field=models.IntegerField(choices=[(1, 'Viber'), (2, 'Telegram'), (3, 'WhatsApp'), (4, 'another')], default=1),
        ),
    ]
