# Generated by Django 3.0.8 on 2020-07-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20200725_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[(9, '9-10'), (10, '10-11'), (11, '11-12'), (12, '12-13'), (13, '13-14'), (14, '14-15'), (15, '15-16'), (16, '16-17'), (17, '17-18'), (18, '18-19'), (19, '19-20')])),
            ],
        ),
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.IntegerField(choices=[(0, 'ПН'), (1, 'ВТ'), (2, 'СР'), (3, 'ЧТ'), (4, 'ПТ'), (5, 'СБ'), (6, 'ВС')]),
        ),
    ]
