# Generated by Django 3.0.8 on 2020-07-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20200725_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.IntegerField(choices=[(1, 'ПН'), (2, 'ВТ'), (3, 'СР'), (4, 'ЧТ'), (5, 'ПТ'), (6, 'СБ'), (7, 'ВС')]),
        ),
    ]
