# Generated by Django 3.2.5 on 2022-01-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20220120_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-birthday', 'surname'], 'verbose_name': '', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AddField(
            model_name='contract',
            name='comments',
            field=models.CharField(blank=True, max_length=100, verbose_name='Коментарии'),
        ),
    ]
