# Generated by Django 3.0.8 on 2020-08-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20200801_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.IntegerField(choices=[(0, 'ПН'), (1, 'ВТ'), (2, 'СР'), (3, 'ЧТ'), (4, 'ПТ'), (5, 'СБ'), (6, 'ВС')]),
        ),
    ]
